# Mailtrap SMTP Credentials (find these in your Mailtrap.io dashboard)
spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=2525
spring.mail.username=2e63b3a2b943e1
spring.mail.password=c826faea32d9e6
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# This is the 'from' address displayed to the user
app.mail.from=support@train-booking.com

